# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

# Read the Docs configuration file for MkDocs
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    golang: "1.23"
  commands:
    # Install D2 diagramming tool (required by mkdocs-d2-plugin)
    - go install oss.terrastruct.com/d2@latest
  jobs:
    post_checkout:
      # Ensure git history is available for versioning
      - git fetch --unshallow || true

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    # Install the Python packages in editable mode for mkdocstrings
    - method: pip
      path: python/dotpromptz
    - method: pip
      path: python/handlebarrz
    # Install documentation dependencies
    - requirements: docs/requirements.txt
