// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"

	"github.com/google/rules_dart/gazelle/pubspec"
)

type DartDepsJson struct {
	Packages []struct {
		Name         string   `json:"name"`
		Dependencies []string `json:"dependencies"`
	} `json:"packages"`
}

func main() {
	dartBin := flag.String("dart_bin", "dart", "Path to dart binary")
	pkgDir := flag.String("package_dir", ".", "Package directory")
	output := flag.String("output", "dart_deps.bzl", "Output file")
	flag.Parse()

	lockPath := filepath.Join(*pkgDir, "pubspec.lock")
	lockfile, err := pubspec.ParseLockfile(lockPath)
	if err != nil {
		log.Fatalf("Failed to parse lockfile: %v", err)
	}

	// Resolve Graph
	graph, err := getDependencyGraph(*dartBin, *pkgDir)
	if err != nil {
		log.Fatalf("Failed to resolve graph: %v", err)
	}

	// Generate Starlark
	f, err := os.Create(*output)
	if err != nil {
		log.Fatalf("Failed to create output file: %v", err)
	}
	defer f.Close()

	fmt.Fprintln(f, "# Generated by rules_dart gazelle tool. DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "DART_PACKAGES = {")

	// Sort keys
	var keys []string
	for k := range lockfile.Packages {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, name := range keys {
		pkg := lockfile.Packages[name]
		if pkg.Source != "hosted" {
			continue
		}

		hosted, err := pkg.AsHosted()
		if err != nil {
			log.Printf("Skipping non-hosted package %s: %v", name, err)
			continue
		}

		deps := graph[name]
		if deps == nil {
			deps = []string{}
		}
		sort.Strings(deps)

		depsJson, _ := json.Marshal(deps)

		fmt.Fprintf(f, "    \"%s\": {\n", name)
		fmt.Fprintf(f, "        \"name\": \"%s\",\n", name)
		fmt.Fprintf(f, "        \"version\": \"%s\",\n", pkg.Version)
		fmt.Fprintf(f, "        \"sha256\": \"%s\",\n", hosted.Sha256)
		fmt.Fprintf(f, "        \"url\": \"%s\",\n", hosted.Url)
		fmt.Fprintf(f, "        \"deps\": %s,\n", depsJson)
		fmt.Fprintf(f, "    },\n")
	}
	fmt.Fprintln(f, "}")
}

func getDependencyGraph(dartBin string, pkgDir string) (map[string][]string, error) {
	// Ensure resolution
	cmdGet := exec.Command(dartBin, "pub", "get")
	cmdGet.Dir = pkgDir
	if err := cmdGet.Run(); err != nil {
		return nil, fmt.Errorf("dart pub get failed: %w", err)
	}

	cmdDeps := exec.Command(dartBin, "pub", "deps", "--json")
	cmdDeps.Dir = pkgDir
	out, err := cmdDeps.Output()
	if err != nil {
		return nil, fmt.Errorf("dart pub deps failed: %w", err)
	}

	var data DartDepsJson
	if err := json.Unmarshal(out, &data); err != nil {
		return nil, fmt.Errorf("failed to parse deps json: %w", err)
	}

	graph := make(map[string][]string)
	for _, pkg := range data.Packages {
		graph[pkg.Name] = pkg.Dependencies
	}
	return graph, nil
}
