# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Golden test support for Flutter widget testing.

# ELI5 (Explain Like I'm 5)

## What are Golden Tests?

Imagine you take a perfect photograph of your LEGO creation. Later, when you
rebuild it, you compare with the photo to make sure it looks exactly the same.
Golden tests do this for your app's UI!

## How it Works

1. You render a widget to an image
2. Save it as a "golden" (the perfect reference)
3. On future tests, compare new renders against the golden
4. If they differ, the test fails (and shows you the difference!)

## Key Terms

| Term | Description |
|------|-------------|
| **Golden file** | The reference image (png) |
| **matchesGoldenFile** | Flutter matcher for golden comparison |
| **Update goldens** | Regenerate reference images |
| **Visual diff** | Highlighted differences between images |

## Test Flow

```
┌─────────────────────────────────────────────────────────────────────────────┐
│                        Golden Test Workflow                                 │
├─────────────────────────────────────────────────────────────────────────────┤
│                                                                             │
│  First Run (Create Goldens):                                                │
│  ┌─────────────┐   ┌─────────────┐   ┌─────────────┐                       │
│  │ Render      │ → │ Screenshot  │ → │ Save as     │                       │
│  │ Widget      │   │ to PNG      │   │ Golden      │                       │
│  └─────────────┘   └─────────────┘   └─────────────┘                       │
│                                                                             │
│  Subsequent Runs (Compare):                                                 │
│  ┌─────────────┐   ┌─────────────┐   ┌─────────────┐   ┌──────────────┐   │
│  │ Render      │ → │ Screenshot  │ → │ Compare to  │ → │ Pass/Fail    │   │
│  │ Widget      │   │ to PNG      │   │ Golden      │   │ + Diff Image │   │
│  └─────────────┘   └─────────────┘   └─────────────┘   └──────────────┘   │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘
```
"""

load("//private:helpers.bzl", "runfiles_path")

# =============================================================================
# Provider
# =============================================================================

FlutterGoldenInfo = provider(
    doc = "Information about golden test configuration.",
    fields = {
        "golden_dir": "Directory containing golden files",
        "test_target": "Test target that uses these goldens",
        "update_script": "Script to update goldens",
        "diff_report": "Generated diff report (if any)",
    },
)

# =============================================================================
# Golden Test Rule
# =============================================================================

def _flutter_golden_test_impl(ctx):
    """Implementation of flutter_golden_test rule."""
    is_windows = ctx.target_platform_has_constraint(
        ctx.attr._windows_constraint[platform_common.ConstraintValueInfo],
    )

    flutter_bin = ctx.executable.flutter_sdk
    test_files = ctx.files.srcs
    golden_dir = ctx.attr.golden_dir
    threshold = ctx.attr.threshold

    # Create test runner script
    script_ext = ".bat" if is_windows else ".sh"
    runner_script = ctx.actions.declare_file(ctx.label.name + script_ext)

    flutter_path = runfiles_path(flutter_bin)

    # Collect test file paths
    test_paths = " ".join([f.short_path for f in test_files])

    if is_windows:
        content = '''@echo off
setlocal enabledelayedexpansion

REM Flutter Golden Test Runner
REM Generated by rules_flutter

set "RUNFILES=%~dp0"
set "FLUTTER_BIN=%RUNFILES%{flutter_path}"
set "GOLDEN_DIR={golden_dir}"
set "THRESHOLD={threshold}"

echo Running Golden Tests...
echo Golden directory: %GOLDEN_DIR%
echo Pixel threshold: %THRESHOLD%%%
echo.

REM Set up golden file directory
if not exist "%GOLDEN_DIR%" mkdir "%GOLDEN_DIR%"

REM Check if updating goldens
if "%1"=="--update-goldens" (
    echo Updating golden files...
    set "UPDATE_GOLDENS=true"
)

REM Run tests
call "%FLUTTER_BIN%" test {test_paths} ^
    --dart-define=GOLDEN_TOOLKIT_THRESHOLD=%THRESHOLD%

set "RESULT=%errorlevel%"

if %RESULT% neq 0 (
    echo.
    echo Golden tests failed!
    echo Check failures/ directory for diff images.
)

exit /b %RESULT%
'''.format(
            flutter_path = flutter_path.replace("/", "\\"),
            golden_dir = golden_dir.replace("/", "\\"),
            threshold = threshold,
            test_paths = test_paths.replace("/", "\\"),
        )
    else:
        content = '''#!/bin/bash
set -e

# Flutter Golden Test Runner
# Generated by rules_flutter

RUNFILES="${{BASH_SOURCE[0]%/*}}"
FLUTTER_BIN="$RUNFILES/{flutter_path}"
GOLDEN_DIR="{golden_dir}"
THRESHOLD="{threshold}"

echo "Running Golden Tests..."
echo "Golden directory: $GOLDEN_DIR"
echo "Pixel threshold: $THRESHOLD%"
echo

# Set up golden file directory
mkdir -p "$GOLDEN_DIR"

# Check if updating goldens
UPDATE_GOLDENS=""
if [ "$1" = "--update-goldens" ]; then
    echo "Updating golden files..."
    UPDATE_GOLDENS="--update-goldens"
fi

# Run tests
"$FLUTTER_BIN" test {test_paths} \\
    --dart-define=GOLDEN_TOOLKIT_THRESHOLD=$THRESHOLD \\
    $UPDATE_GOLDENS

RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo
    echo "Golden tests failed!"
    echo "Check failures/ directory for diff images."
fi

exit $RESULT
'''.format(
            flutter_path = flutter_path,
            golden_dir = golden_dir,
            threshold = threshold,
            test_paths = test_paths,
        )

    ctx.actions.write(
        output = runner_script,
        content = content,
        is_executable = True,
    )

    # Create update script
    update_script = ctx.actions.declare_file(ctx.label.name + "_update" + script_ext)

    if is_windows:
        update_content = '''@echo off
call "{runner}" --update-goldens
'''.format(runner = runner_script.basename)
    else:
        update_content = '''#!/bin/bash
"{runner}" --update-goldens
'''.format(runner = runner_script.path)

    ctx.actions.write(
        output = update_script,
        content = update_content,
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = [flutter_bin] + test_files)

    return [
        DefaultInfo(
            executable = runner_script,
            runfiles = runfiles,
        ),
        FlutterGoldenInfo(
            golden_dir = golden_dir,
            test_target = ctx.label,
            update_script = update_script,
            diff_report = None,
        ),
    ]

_flutter_golden_test = rule(
    implementation = _flutter_golden_test_impl,
    attrs = {
        "srcs": attr.label_list(
            doc = "Test source files containing golden tests.",
            allow_files = [".dart"],
            mandatory = True,
        ),
        "golden_dir": attr.string(
            doc = "Directory containing golden files.",
            default = "test/goldens",
        ),
        "threshold": attr.int(
            doc = "Pixel difference threshold percentage (0-100).",
            default = 0,
        ),
        "flutter_sdk": attr.label(
            doc = "Flutter SDK executable.",
            default = Label("@flutter_sdk//:flutter_bin"),
            executable = True,
            cfg = "exec",
            allow_single_file = True,
        ),
        "_windows_constraint": attr.label(
            default = Label("@platforms//os:windows"),
        ),
    },
    test = True,
    doc = "Runs Flutter golden (screenshot) tests.",
)

# =============================================================================
# Golden Update Rule
# =============================================================================

def _flutter_update_goldens_impl(ctx):
    """Implementation of flutter_update_goldens rule."""
    is_windows = ctx.target_platform_has_constraint(
        ctx.attr._windows_constraint[platform_common.ConstraintValueInfo],
    )

    flutter_bin = ctx.executable.flutter_sdk
    test_dir = ctx.attr.test_dir
    golden_dir = ctx.attr.golden_dir

    script_ext = ".bat" if is_windows else ".sh"
    runner_script = ctx.actions.declare_file(ctx.label.name + script_ext)

    flutter_path = runfiles_path(flutter_bin)

    if is_windows:
        content = '''@echo off
setlocal

set "RUNFILES=%~dp0"
set "FLUTTER_BIN=%RUNFILES%{flutter_path}"

echo Updating Golden Files...
echo.

call "%FLUTTER_BIN%" test --update-goldens {test_dir}

echo.
echo Golden files updated in {golden_dir}
echo Please review and commit the changes.
'''.format(
            flutter_path = flutter_path.replace("/", "\\"),
            test_dir = test_dir.replace("/", "\\"),
            golden_dir = golden_dir.replace("/", "\\"),
        )
    else:
        content = '''#!/bin/bash
set -e

RUNFILES="${{BASH_SOURCE[0]%/*}}"
FLUTTER_BIN="$RUNFILES/{flutter_path}"

echo "Updating Golden Files..."
echo

"$FLUTTER_BIN" test --update-goldens {test_dir}

echo
echo "Golden files updated in {golden_dir}"
echo "Please review and commit the changes."
'''.format(
            flutter_path = flutter_path,
            test_dir = test_dir,
            golden_dir = golden_dir,
        )

    ctx.actions.write(
        output = runner_script,
        content = content,
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = [flutter_bin])

    return [DefaultInfo(executable = runner_script, runfiles = runfiles)]

_flutter_update_goldens = rule(
    implementation = _flutter_update_goldens_impl,
    attrs = {
        "test_dir": attr.string(
            doc = "Directory containing golden tests.",
            default = "test",
        ),
        "golden_dir": attr.string(
            doc = "Directory containing golden files.",
            default = "test/goldens",
        ),
        "flutter_sdk": attr.label(
            doc = "Flutter SDK executable.",
            default = Label("@flutter_sdk//:flutter_bin"),
            executable = True,
            cfg = "exec",
            allow_single_file = True,
        ),
        "_windows_constraint": attr.label(
            default = Label("@platforms//os:windows"),
        ),
    },
    executable = True,
    doc = "Updates golden files by re-running golden tests.",
)

# =============================================================================
# Golden Diff Report Rule
# =============================================================================

def _flutter_golden_report_impl(ctx):
    """Generate an HTML diff report for failed golden tests."""
    report_file = ctx.actions.declare_file(ctx.label.name + ".html")

    # Template for diff report
    content = '''<!DOCTYPE html>
<html>
<head>
    <title>Golden Test Diff Report</title>
    <style>
        body {{ font-family: -apple-system, system-ui, sans-serif; margin: 20px; }}
        h1 {{ color: #333; }}
        .diff-container {{ display: flex; gap: 20px; margin: 20px 0; }}
        .image-box {{ text-align: center; }}
        .image-box img {{ max-width: 400px; border: 1px solid #ccc; }}
        .passed {{ color: #28a745; }}
        .failed {{ color: #dc3545; }}
        .summary {{ background: #f8f9fa; padding: 15px; border-radius: 5px; }}
    </style>
</head>
<body>
    <h1>Golden Test Diff Report</h1>
    <div class="summary">
        <p>Generated by <code>rules_flutter</code> golden test support.</p>
        <p>Run <code>bazel run //:{update_target}</code> to update goldens.</p>
    </div>
    <div id="diffs">
        <!-- Diff comparisons will be inserted here by the test runner -->
        <p>No failures detected. All golden tests passed!</p>
    </div>
</body>
</html>
'''.format(update_target = ctx.attr.update_target)

    ctx.actions.write(
        output = report_file,
        content = content,
    )

    return [DefaultInfo(files = depset([report_file]))]

flutter_golden_report = rule(
    implementation = _flutter_golden_report_impl,
    attrs = {
        "update_target": attr.string(
            doc = "Name of the update goldens target.",
            default = "update_goldens",
        ),
    },
    doc = "Generates an HTML diff report for golden test failures.",
)

# =============================================================================
# Public Macros
# =============================================================================

def flutter_golden_test(
        name,
        srcs,
        golden_dir = "test/goldens",
        threshold = 0,
        visibility = None,
        **kwargs):
    """Create a golden test target for Flutter widgets.

    Golden tests capture screenshots of widgets and compare them against
    saved "golden" reference images.

    Args:
        name: Name of the test target.
        srcs: Test source files containing matchesGoldenFile calls.
        golden_dir: Directory containing golden reference images.
        threshold: Pixel difference threshold (0-100). 0 means exact match.
        visibility: Target visibility.
        **kwargs: Additional arguments.

    Example:
        ```python
        flutter_golden_test(
            name = "widget_golden_test",
            srcs = ["test/widget_golden_test.dart"],
            golden_dir = "test/goldens",
            threshold = 1,  # Allow 1% pixel difference
        )
        ```

        In your test file:
        ```dart
        testWidgets('MyWidget golden', (tester) async {
          await tester.pumpWidget(MyWidget());
          await expectLater(
            find.byType(MyWidget),
            matchesGoldenFile('goldens/my_widget.png'),
          );
        });
        ```
    """
    _flutter_golden_test(
        name = name,
        srcs = srcs,
        golden_dir = golden_dir,
        threshold = threshold,
        visibility = visibility,
        **kwargs
    )

    # Create update target
    _flutter_update_goldens(
        name = name + "_update",
        test_dir = "test",
        golden_dir = golden_dir,
        visibility = visibility,
    )

def flutter_update_goldens(
        name,
        test_dir = "test",
        golden_dir = "test/goldens",
        visibility = None,
        **kwargs):
    """Create a target to update golden reference images.

    Args:
        name: Name of the target.
        test_dir: Directory containing golden tests.
        golden_dir: Directory to store golden images.
        visibility: Target visibility.
        **kwargs: Additional arguments.

    Example:
        ```python
        flutter_update_goldens(
            name = "update_goldens",
        )
        ```

        Then run: `bazel run //:update_goldens`
    """
    _flutter_update_goldens(
        name = name,
        test_dir = test_dir,
        golden_dir = golden_dir,
        visibility = visibility,
        **kwargs
    )
