#!/usr/bin/env bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# Usage: ./scripts/publish-java.sh <gpg_sign_key_path> <gpg_passphrase> <maven_user> <maven_password>

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <gpg_sign_key_path> <gpg_passphrase> <maven_user> <maven_password>"
    exit 1
fi

GPG_KEY_PATH=$1
GPG_PASSPHRASE=$2
MAVEN_USER=$3
MAVEN_PASSWORD=$4

# Define the deployment repository URL (Sonatype OSSRH)
DEPLOY_ENV="release" # or "snapshot" if desired, but typically we want release for tags.
# Bazel java_export allows specifying deployment via flags or properties.
# We will use the standard command structure generated by java_export.

echo "Publishing Java artifacts..."

bazel run //java/com/google/dotprompt:dotprompt_pkg.publish -- \
    --define "maven_repo=https://oss.sonatype.org/service/local/staging/deploy/maven2/" \
    --define "maven_user=$MAVEN_USER" \
    --define "maven_password=$MAVEN_PASSWORD" \
    --define "gpg_sign=true" \
    --define "gpg_key=$GPG_KEY_PATH" \
    --define "gpg_passphrase=$GPG_PASSPHRASE"

echo "Publishing complete."
