// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED FILE - DO NOT EDIT
// Generated by: scripts/generate_handlebars_parser
// Source: spec/handlebars/antlr/Handlebars*.g4

// Generated from HandlebarsParser.g4 by ANTLR 4.13.2
// ignore_for_file: unused_import, unused_local_variable, prefer_single_quotes
import "package:antlr4/antlr4.dart";

import "HandlebarsParser.dart";

/// This abstract class defines a complete generic visitor for a parse tree
/// produced by [HandlebarsParser].
///
/// [T] is the eturn type of the visit operation. Use `void` for
/// operations with no return type.
abstract class HandlebarsParserVisitor<T> extends ParseTreeVisitor<T> {
  /// Visit a parse tree produced by [HandlebarsParser.root].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitRoot(RootContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.program].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitProgram(ProgramContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.statement].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitStatement(StatementContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.content].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitContent(ContentContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.comment].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitComment(CommentContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.rawBlock].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitRawBlock(RawBlockContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.openRawBlock].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitOpenRawBlock(OpenRawBlockContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.block].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitBlock(BlockContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.openBlock].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitOpenBlock(OpenBlockContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.openInverse].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitOpenInverse(OpenInverseContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.openInverseChain].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitOpenInverseChain(OpenInverseChainContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.inverseAndProgram].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitInverseAndProgram(InverseAndProgramContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.inverseChain].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitInverseChain(InverseChainContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.closeBlock].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitCloseBlock(CloseBlockContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.mustache].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitMustache(MustacheContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.partial].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitPartial(PartialContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.partialBlock].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitPartialBlock(PartialBlockContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.openPartialBlock].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitOpenPartialBlock(OpenPartialBlockContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.param].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitParam(ParamContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.sexpr].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitSexpr(SexprContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.hash].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitHash(HashContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.hashSegment].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitHashSegment(HashSegmentContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.blockParams].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitBlockParams(BlockParamsContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.helperName].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitHelperName(HelperNameContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.partialName].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitPartialName(PartialNameContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.dataName].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitDataName(DataNameContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.path].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitPath(PathContext ctx);

  /// Visit a parse tree produced by [HandlebarsParser.pathSegments].
  /// [ctx] the parse tree.
  /// Return the visitor result.
  T? visitPathSegments(PathSegmentsContext ctx);
}
