// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED FILE - DO NOT EDIT
// Generated by: scripts/generate_handlebars_parser
// Source: spec/handlebars/antlr/Handlebars*.g4

// Generated from HandlebarsParser.g4 by ANTLR 4.13.2
// ignore_for_file: unused_import, unused_local_variable, prefer_single_quotes
import "package:antlr4/antlr4.dart";

import "HandlebarsParserBaseVisitor.dart";
import "HandlebarsParserVisitor.dart";

const int RULE_root = 0;
const int RULE_program = 1;
const int RULE_statement = 2;
const int RULE_content = 3;
const int RULE_comment = 4;
const int RULE_rawBlock = 5;
const int RULE_openRawBlock = 6;
const int RULE_block = 7;
const int RULE_openBlock = 8;
const int RULE_openInverse = 9;
const int RULE_openInverseChain = 10;
const int RULE_inverseAndProgram = 11;
const int RULE_inverseChain = 12;
const int RULE_closeBlock = 13;
const int RULE_mustache = 14;
const int RULE_partial = 15;
const int RULE_partialBlock = 16;
const int RULE_openPartialBlock = 17;
const int RULE_param = 18;
const int RULE_sexpr = 19;
const int RULE_hash = 20;
const int RULE_hashSegment = 21;
const int RULE_blockParams = 22;
const int RULE_helperName = 23;
const int RULE_partialName = 24;
const int RULE_dataName = 25;
const int RULE_path = 26;
const int RULE_pathSegments = 27;

class HandlebarsParser extends Parser {
  HandlebarsParser(super.input) {
    interpreter = ParserATNSimulator(this, _ATN, _decisionToDFA, _sharedContextCache);
  }
  static final checkVersion = () => RuntimeMetaData.checkVersion("4.13.2", RuntimeMetaData.VERSION);
  static const int TOKEN_EOF = IntStream.EOF;

  static final List<DFA> _decisionToDFA = List.generate(
    _ATN.numberOfDecisions,
    (i) => DFA(_ATN.getDecisionState(i), i),
  );
  static final PredictionContextCache _sharedContextCache = PredictionContextCache();
  static const int TOKEN_OPEN_RAW_BLOCK = 1;
  static const int TOKEN_END_RAW_BLOCK = 2;
  static const int TOKEN_OPEN_UNESCAPED = 3;
  static const int TOKEN_OPEN_PARTIAL_BLOCK = 4;
  static const int TOKEN_OPEN_BLOCK = 5;
  static const int TOKEN_OPEN_ENDBLOCK = 6;
  static const int TOKEN_INVERSE = 7;
  static const int TOKEN_OPEN_INVERSE = 8;
  static const int TOKEN_OPEN_INVERSE_CHAIN = 9;
  static const int TOKEN_OPEN_PARTIAL = 10;
  static const int TOKEN_COMMENT = 11;
  static const int TOKEN_OPEN = 12;
  static const int TOKEN_CONTENT = 13;
  static const int TOKEN_CLOSE_RAW_BLOCK = 14;
  static const int TOKEN_CLOSE_UNESCAPED = 15;
  static const int TOKEN_CLOSE = 16;
  static const int TOKEN_OPEN_SEXPR = 17;
  static const int TOKEN_CLOSE_SEXPR = 18;
  static const int TOKEN_OPEN_BLOCK_PARAMS = 19;
  static const int TOKEN_CLOSE_BLOCK_PARAMS = 20;
  static const int TOKEN_SEP = 21;
  static const int TOKEN_EQUALS = 22;
  static const int TOKEN_STRING = 23;
  static const int TOKEN_NUMBER = 24;
  static const int TOKEN_BOOLEAN = 25;
  static const int TOKEN_UNDEFINED = 26;
  static const int TOKEN_NULL_LIT = 27;
  static const int TOKEN_DATA = 28;
  static const int TOKEN_ID = 29;
  static const int TOKEN_WS = 30;
  static const int TOKEN_ESC_VAR = 31;

  @override
  final List<String> ruleNames = [
    "root",
    "program",
    "statement",
    "content",
    "comment",
    "rawBlock",
    "openRawBlock",
    "block",
    "openBlock",
    "openInverse",
    "openInverseChain",
    "inverseAndProgram",
    "inverseChain",
    "closeBlock",
    "mustache",
    "partial",
    "partialBlock",
    "openPartialBlock",
    "param",
    "sexpr",
    "hash",
    "hashSegment",
    "blockParams",
    "helperName",
    "partialName",
    "dataName",
    "path",
    "pathSegments",
  ];

  static final List<String?> _LITERAL_NAMES = [
    null,
    "'{{{{'",
    "'{{{{/'",
    "'{{{'",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "'}}}}'",
    null,
    null,
    "'('",
    "')'",
    null,
    "'|'",
    null,
    "'='",
    null,
    null,
    null,
    "'undefined'",
    "'null'",
    "'@'",
    null,
    null,
    r"'\{{'",
  ];
  static final List<String?> _SYMBOLIC_NAMES = [
    null,
    "OPEN_RAW_BLOCK",
    "END_RAW_BLOCK",
    "OPEN_UNESCAPED",
    "OPEN_PARTIAL_BLOCK",
    "OPEN_BLOCK",
    "OPEN_ENDBLOCK",
    "INVERSE",
    "OPEN_INVERSE",
    "OPEN_INVERSE_CHAIN",
    "OPEN_PARTIAL",
    "COMMENT",
    "OPEN",
    "CONTENT",
    "CLOSE_RAW_BLOCK",
    "CLOSE_UNESCAPED",
    "CLOSE",
    "OPEN_SEXPR",
    "CLOSE_SEXPR",
    "OPEN_BLOCK_PARAMS",
    "CLOSE_BLOCK_PARAMS",
    "SEP",
    "EQUALS",
    "STRING",
    "NUMBER",
    "BOOLEAN",
    "UNDEFINED",
    "NULL_LIT",
    "DATA",
    "ID",
    "WS",
    "ESC_VAR",
  ];
  static final Vocabulary VOCABULARY = VocabularyImpl(_LITERAL_NAMES, _SYMBOLIC_NAMES);

  @override
  Vocabulary get vocabulary => VOCABULARY;

  @override
  String get grammarFileName => "HandlebarsParser.g4";

  @override
  List<int> get serializedATN => _serializedATN;

  @override
  ATN getATN() => _ATN;

  RootContext root() {
    final dynamic localctx = RootContext(context, state);
    enterRule(localctx, 0, RULE_root);
    try {
      enterOuterAlt(localctx, 1);
      state = 56;
      program();
      state = 57;
      match(TOKEN_EOF);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  ProgramContext program() {
    final dynamic localctx = ProgramContext(context, state);
    enterRule(localctx, 2, RULE_program);
    int la;
    try {
      enterOuterAlt(localctx, 1);
      state = 62;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      while ((la & ~0x3f) == 0 && ((1 << la) & 15674) != 0) {
        state = 59;
        statement();
        state = 64;
        errorHandler.sync(this);
        la = tokenStream.LA(1)!;
      }
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  StatementContext statement() {
    final dynamic localctx = StatementContext(context, state);
    enterRule(localctx, 4, RULE_statement);
    try {
      state = 72;
      errorHandler.sync(this);
      switch (tokenStream.LA(1)!) {
        case TOKEN_OPEN_UNESCAPED:
        case TOKEN_OPEN:
          enterOuterAlt(localctx, 1);
          state = 65;
          mustache();
        case TOKEN_OPEN_BLOCK:
        case TOKEN_OPEN_INVERSE:
          enterOuterAlt(localctx, 2);
          state = 66;
          block();
        case TOKEN_OPEN_RAW_BLOCK:
          enterOuterAlt(localctx, 3);
          state = 67;
          rawBlock();
        case TOKEN_OPEN_PARTIAL:
          enterOuterAlt(localctx, 4);
          state = 68;
          partial();
        case TOKEN_OPEN_PARTIAL_BLOCK:
          enterOuterAlt(localctx, 5);
          state = 69;
          partialBlock();
        case TOKEN_CONTENT:
          enterOuterAlt(localctx, 6);
          state = 70;
          content();
        case TOKEN_COMMENT:
          enterOuterAlt(localctx, 7);
          state = 71;
          comment();
        default:
          throw NoViableAltException(this);
      }
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  ContentContext content() {
    final dynamic localctx = ContentContext(context, state);
    enterRule(localctx, 6, RULE_content);
    try {
      enterOuterAlt(localctx, 1);
      state = 74;
      match(TOKEN_CONTENT);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  CommentContext comment() {
    final dynamic localctx = CommentContext(context, state);
    enterRule(localctx, 8, RULE_comment);
    try {
      enterOuterAlt(localctx, 1);
      state = 76;
      match(TOKEN_COMMENT);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  RawBlockContext rawBlock() {
    final dynamic localctx = RawBlockContext(context, state);
    enterRule(localctx, 10, RULE_rawBlock);
    try {
      enterOuterAlt(localctx, 1);
      state = 78;
      openRawBlock();
      state = 79;
      program();
      state = 80;
      match(TOKEN_END_RAW_BLOCK);
      state = 81;
      helperName();
      state = 82;
      match(TOKEN_CLOSE_RAW_BLOCK);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  OpenRawBlockContext openRawBlock() {
    final dynamic localctx = OpenRawBlockContext(context, state);
    enterRule(localctx, 12, RULE_openRawBlock);
    int la;
    try {
      int alt;
      enterOuterAlt(localctx, 1);
      state = 84;
      match(TOKEN_OPEN_RAW_BLOCK);
      state = 85;
      helperName();
      state = 89;
      errorHandler.sync(this);
      alt = interpreter!.adaptivePredict(tokenStream, 2, context);
      while (alt != 2 && alt != ATN.INVALID_ALT_NUMBER) {
        if (alt == 1) {
          state = 86;
          param();
        }
        state = 91;
        errorHandler.sync(this);
        alt = interpreter!.adaptivePredict(tokenStream, 2, context);
      }
      state = 93;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      if (la == TOKEN_ID) {
        state = 92;
        hash();
      }

      state = 95;
      match(TOKEN_CLOSE_RAW_BLOCK);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  BlockContext block() {
    final dynamic localctx = BlockContext(context, state);
    enterRule(localctx, 14, RULE_block);
    int la;
    try {
      state = 111;
      errorHandler.sync(this);
      switch (tokenStream.LA(1)!) {
        case TOKEN_OPEN_BLOCK:
          enterOuterAlt(localctx, 1);
          state = 97;
          openBlock();
          state = 98;
          program();
          state = 100;
          errorHandler.sync(this);
          la = tokenStream.LA(1)!;
          if (la == TOKEN_INVERSE || la == TOKEN_OPEN_INVERSE_CHAIN) {
            state = 99;
            inverseChain();
          }

          state = 102;
          closeBlock();
        case TOKEN_OPEN_INVERSE:
          enterOuterAlt(localctx, 2);
          state = 104;
          openInverse();
          state = 105;
          program();
          state = 107;
          errorHandler.sync(this);
          la = tokenStream.LA(1)!;
          if (la == TOKEN_INVERSE) {
            state = 106;
            inverseAndProgram();
          }

          state = 109;
          closeBlock();
        default:
          throw NoViableAltException(this);
      }
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  OpenBlockContext openBlock() {
    final dynamic localctx = OpenBlockContext(context, state);
    enterRule(localctx, 16, RULE_openBlock);
    int la;
    try {
      int alt;
      enterOuterAlt(localctx, 1);
      state = 113;
      match(TOKEN_OPEN_BLOCK);
      state = 114;
      helperName();
      state = 118;
      errorHandler.sync(this);
      alt = interpreter!.adaptivePredict(tokenStream, 7, context);
      while (alt != 2 && alt != ATN.INVALID_ALT_NUMBER) {
        if (alt == 1) {
          state = 115;
          param();
        }
        state = 120;
        errorHandler.sync(this);
        alt = interpreter!.adaptivePredict(tokenStream, 7, context);
      }
      state = 122;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      if (la == TOKEN_ID) {
        state = 121;
        hash();
      }

      state = 125;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      if (la == TOKEN_OPEN_BLOCK_PARAMS) {
        state = 124;
        blockParams();
      }

      state = 127;
      match(TOKEN_CLOSE);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  OpenInverseContext openInverse() {
    final dynamic localctx = OpenInverseContext(context, state);
    enterRule(localctx, 18, RULE_openInverse);
    int la;
    try {
      int alt;
      enterOuterAlt(localctx, 1);
      state = 129;
      match(TOKEN_OPEN_INVERSE);
      state = 130;
      helperName();
      state = 134;
      errorHandler.sync(this);
      alt = interpreter!.adaptivePredict(tokenStream, 10, context);
      while (alt != 2 && alt != ATN.INVALID_ALT_NUMBER) {
        if (alt == 1) {
          state = 131;
          param();
        }
        state = 136;
        errorHandler.sync(this);
        alt = interpreter!.adaptivePredict(tokenStream, 10, context);
      }
      state = 138;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      if (la == TOKEN_ID) {
        state = 137;
        hash();
      }

      state = 141;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      if (la == TOKEN_OPEN_BLOCK_PARAMS) {
        state = 140;
        blockParams();
      }

      state = 143;
      match(TOKEN_CLOSE);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  OpenInverseChainContext openInverseChain() {
    final dynamic localctx = OpenInverseChainContext(context, state);
    enterRule(localctx, 20, RULE_openInverseChain);
    int la;
    try {
      int alt;
      enterOuterAlt(localctx, 1);
      state = 145;
      match(TOKEN_OPEN_INVERSE_CHAIN);
      state = 146;
      helperName();
      state = 150;
      errorHandler.sync(this);
      alt = interpreter!.adaptivePredict(tokenStream, 13, context);
      while (alt != 2 && alt != ATN.INVALID_ALT_NUMBER) {
        if (alt == 1) {
          state = 147;
          param();
        }
        state = 152;
        errorHandler.sync(this);
        alt = interpreter!.adaptivePredict(tokenStream, 13, context);
      }
      state = 154;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      if (la == TOKEN_ID) {
        state = 153;
        hash();
      }

      state = 157;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      if (la == TOKEN_OPEN_BLOCK_PARAMS) {
        state = 156;
        blockParams();
      }

      state = 159;
      match(TOKEN_CLOSE);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  InverseAndProgramContext inverseAndProgram() {
    final dynamic localctx = InverseAndProgramContext(context, state);
    enterRule(localctx, 22, RULE_inverseAndProgram);
    try {
      enterOuterAlt(localctx, 1);
      state = 161;
      match(TOKEN_INVERSE);
      state = 162;
      program();
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  InverseChainContext inverseChain() {
    final dynamic localctx = InverseChainContext(context, state);
    enterRule(localctx, 24, RULE_inverseChain);
    int la;
    try {
      state = 170;
      errorHandler.sync(this);
      switch (tokenStream.LA(1)!) {
        case TOKEN_OPEN_INVERSE_CHAIN:
          enterOuterAlt(localctx, 1);
          state = 164;
          openInverseChain();
          state = 165;
          program();
          state = 167;
          errorHandler.sync(this);
          la = tokenStream.LA(1)!;
          if (la == TOKEN_INVERSE || la == TOKEN_OPEN_INVERSE_CHAIN) {
            state = 166;
            inverseChain();
          }

        case TOKEN_INVERSE:
          enterOuterAlt(localctx, 2);
          state = 169;
          inverseAndProgram();
        default:
          throw NoViableAltException(this);
      }
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  CloseBlockContext closeBlock() {
    final dynamic localctx = CloseBlockContext(context, state);
    enterRule(localctx, 26, RULE_closeBlock);
    try {
      enterOuterAlt(localctx, 1);
      state = 172;
      match(TOKEN_OPEN_ENDBLOCK);
      state = 173;
      helperName();
      state = 174;
      match(TOKEN_CLOSE);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  MustacheContext mustache() {
    final dynamic localctx = MustacheContext(context, state);
    enterRule(localctx, 28, RULE_mustache);
    int la;
    try {
      int alt;
      state = 202;
      errorHandler.sync(this);
      switch (tokenStream.LA(1)!) {
        case TOKEN_OPEN:
          enterOuterAlt(localctx, 1);
          state = 176;
          match(TOKEN_OPEN);
          state = 177;
          helperName();
          state = 181;
          errorHandler.sync(this);
          alt = interpreter!.adaptivePredict(tokenStream, 18, context);
          while (alt != 2 && alt != ATN.INVALID_ALT_NUMBER) {
            if (alt == 1) {
              state = 178;
              param();
            }
            state = 183;
            errorHandler.sync(this);
            alt = interpreter!.adaptivePredict(tokenStream, 18, context);
          }
          state = 185;
          errorHandler.sync(this);
          la = tokenStream.LA(1)!;
          if (la == TOKEN_ID) {
            state = 184;
            hash();
          }

          state = 187;
          match(TOKEN_CLOSE);
        case TOKEN_OPEN_UNESCAPED:
          enterOuterAlt(localctx, 2);
          state = 189;
          match(TOKEN_OPEN_UNESCAPED);
          state = 190;
          helperName();
          state = 194;
          errorHandler.sync(this);
          alt = interpreter!.adaptivePredict(tokenStream, 20, context);
          while (alt != 2 && alt != ATN.INVALID_ALT_NUMBER) {
            if (alt == 1) {
              state = 191;
              param();
            }
            state = 196;
            errorHandler.sync(this);
            alt = interpreter!.adaptivePredict(tokenStream, 20, context);
          }
          state = 198;
          errorHandler.sync(this);
          la = tokenStream.LA(1)!;
          if (la == TOKEN_ID) {
            state = 197;
            hash();
          }

          state = 200;
          match(TOKEN_CLOSE_UNESCAPED);
        default:
          throw NoViableAltException(this);
      }
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  PartialContext partial() {
    final dynamic localctx = PartialContext(context, state);
    enterRule(localctx, 30, RULE_partial);
    int la;
    try {
      int alt;
      enterOuterAlt(localctx, 1);
      state = 204;
      match(TOKEN_OPEN_PARTIAL);
      state = 205;
      partialName();
      state = 209;
      errorHandler.sync(this);
      alt = interpreter!.adaptivePredict(tokenStream, 23, context);
      while (alt != 2 && alt != ATN.INVALID_ALT_NUMBER) {
        if (alt == 1) {
          state = 206;
          param();
        }
        state = 211;
        errorHandler.sync(this);
        alt = interpreter!.adaptivePredict(tokenStream, 23, context);
      }
      state = 213;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      if (la == TOKEN_ID) {
        state = 212;
        hash();
      }

      state = 215;
      match(TOKEN_CLOSE);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  PartialBlockContext partialBlock() {
    final dynamic localctx = PartialBlockContext(context, state);
    enterRule(localctx, 32, RULE_partialBlock);
    try {
      enterOuterAlt(localctx, 1);
      state = 217;
      openPartialBlock();
      state = 218;
      program();
      state = 219;
      closeBlock();
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  OpenPartialBlockContext openPartialBlock() {
    final dynamic localctx = OpenPartialBlockContext(context, state);
    enterRule(localctx, 34, RULE_openPartialBlock);
    int la;
    try {
      int alt;
      enterOuterAlt(localctx, 1);
      state = 221;
      match(TOKEN_OPEN_PARTIAL_BLOCK);
      state = 222;
      partialName();
      state = 226;
      errorHandler.sync(this);
      alt = interpreter!.adaptivePredict(tokenStream, 25, context);
      while (alt != 2 && alt != ATN.INVALID_ALT_NUMBER) {
        if (alt == 1) {
          state = 223;
          param();
        }
        state = 228;
        errorHandler.sync(this);
        alt = interpreter!.adaptivePredict(tokenStream, 25, context);
      }
      state = 230;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      if (la == TOKEN_ID) {
        state = 229;
        hash();
      }

      state = 232;
      match(TOKEN_CLOSE);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  ParamContext param() {
    final dynamic localctx = ParamContext(context, state);
    enterRule(localctx, 36, RULE_param);
    try {
      state = 236;
      errorHandler.sync(this);
      switch (tokenStream.LA(1)!) {
        case TOKEN_STRING:
        case TOKEN_NUMBER:
        case TOKEN_BOOLEAN:
        case TOKEN_UNDEFINED:
        case TOKEN_NULL_LIT:
        case TOKEN_DATA:
        case TOKEN_ID:
          enterOuterAlt(localctx, 1);
          state = 234;
          helperName();
        case TOKEN_OPEN_SEXPR:
          enterOuterAlt(localctx, 2);
          state = 235;
          sexpr();
        default:
          throw NoViableAltException(this);
      }
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  SexprContext sexpr() {
    final dynamic localctx = SexprContext(context, state);
    enterRule(localctx, 38, RULE_sexpr);
    int la;
    try {
      int alt;
      enterOuterAlt(localctx, 1);
      state = 238;
      match(TOKEN_OPEN_SEXPR);
      state = 239;
      helperName();
      state = 243;
      errorHandler.sync(this);
      alt = interpreter!.adaptivePredict(tokenStream, 28, context);
      while (alt != 2 && alt != ATN.INVALID_ALT_NUMBER) {
        if (alt == 1) {
          state = 240;
          param();
        }
        state = 245;
        errorHandler.sync(this);
        alt = interpreter!.adaptivePredict(tokenStream, 28, context);
      }
      state = 247;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      if (la == TOKEN_ID) {
        state = 246;
        hash();
      }

      state = 249;
      match(TOKEN_CLOSE_SEXPR);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  HashContext hash() {
    final dynamic localctx = HashContext(context, state);
    enterRule(localctx, 40, RULE_hash);
    int la;
    try {
      enterOuterAlt(localctx, 1);
      state = 252;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      do {
        state = 251;
        hashSegment();
        state = 254;
        errorHandler.sync(this);
        la = tokenStream.LA(1)!;
      } while (la == TOKEN_ID);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  HashSegmentContext hashSegment() {
    final dynamic localctx = HashSegmentContext(context, state);
    enterRule(localctx, 42, RULE_hashSegment);
    try {
      enterOuterAlt(localctx, 1);
      state = 256;
      match(TOKEN_ID);
      state = 257;
      match(TOKEN_EQUALS);
      state = 258;
      param();
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  BlockParamsContext blockParams() {
    final dynamic localctx = BlockParamsContext(context, state);
    enterRule(localctx, 44, RULE_blockParams);
    int la;
    try {
      enterOuterAlt(localctx, 1);
      state = 260;
      match(TOKEN_OPEN_BLOCK_PARAMS);
      state = 262;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      do {
        state = 261;
        match(TOKEN_ID);
        state = 264;
        errorHandler.sync(this);
        la = tokenStream.LA(1)!;
      } while (la == TOKEN_ID);
      state = 266;
      match(TOKEN_CLOSE_BLOCK_PARAMS);
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  HelperNameContext helperName() {
    final dynamic localctx = HelperNameContext(context, state);
    enterRule(localctx, 46, RULE_helperName);
    try {
      state = 275;
      errorHandler.sync(this);
      switch (tokenStream.LA(1)!) {
        case TOKEN_ID:
          enterOuterAlt(localctx, 1);
          state = 268;
          path();
        case TOKEN_DATA:
          enterOuterAlt(localctx, 2);
          state = 269;
          dataName();
        case TOKEN_STRING:
          enterOuterAlt(localctx, 3);
          state = 270;
          match(TOKEN_STRING);
        case TOKEN_NUMBER:
          enterOuterAlt(localctx, 4);
          state = 271;
          match(TOKEN_NUMBER);
        case TOKEN_BOOLEAN:
          enterOuterAlt(localctx, 5);
          state = 272;
          match(TOKEN_BOOLEAN);
        case TOKEN_UNDEFINED:
          enterOuterAlt(localctx, 6);
          state = 273;
          match(TOKEN_UNDEFINED);
        case TOKEN_NULL_LIT:
          enterOuterAlt(localctx, 7);
          state = 274;
          match(TOKEN_NULL_LIT);
        default:
          throw NoViableAltException(this);
      }
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  PartialNameContext partialName() {
    final dynamic localctx = PartialNameContext(context, state);
    enterRule(localctx, 48, RULE_partialName);
    try {
      state = 279;
      errorHandler.sync(this);
      switch (tokenStream.LA(1)!) {
        case TOKEN_STRING:
        case TOKEN_NUMBER:
        case TOKEN_BOOLEAN:
        case TOKEN_UNDEFINED:
        case TOKEN_NULL_LIT:
        case TOKEN_DATA:
        case TOKEN_ID:
          enterOuterAlt(localctx, 1);
          state = 277;
          helperName();
        case TOKEN_OPEN_SEXPR:
          enterOuterAlt(localctx, 2);
          state = 278;
          sexpr();
        default:
          throw NoViableAltException(this);
      }
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  DataNameContext dataName() {
    final dynamic localctx = DataNameContext(context, state);
    enterRule(localctx, 50, RULE_dataName);
    try {
      enterOuterAlt(localctx, 1);
      state = 281;
      match(TOKEN_DATA);
      state = 282;
      pathSegments();
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  PathContext path() {
    final dynamic localctx = PathContext(context, state);
    enterRule(localctx, 52, RULE_path);
    try {
      enterOuterAlt(localctx, 1);
      state = 284;
      pathSegments();
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  PathSegmentsContext pathSegments() {
    final dynamic localctx = PathSegmentsContext(context, state);
    enterRule(localctx, 54, RULE_pathSegments);
    int la;
    try {
      enterOuterAlt(localctx, 1);
      state = 286;
      match(TOKEN_ID);
      state = 291;
      errorHandler.sync(this);
      la = tokenStream.LA(1)!;
      while (la == TOKEN_SEP) {
        state = 287;
        match(TOKEN_SEP);
        state = 288;
        match(TOKEN_ID);
        state = 293;
        errorHandler.sync(this);
        la = tokenStream.LA(1)!;
      }
    } on RecognitionException catch (re) {
      localctx.exception = re;
      errorHandler.reportError(this, re);
      errorHandler.recover(this, re);
    } finally {
      exitRule();
    }
    return localctx;
  }

  static const List<int> _serializedATN = [
    4,
    1,
    31,
    295,
    2,
    0,
    7,
    0,
    2,
    1,
    7,
    1,
    2,
    2,
    7,
    2,
    2,
    3,
    7,
    3,
    2,
    4,
    7,
    4,
    2,
    5,
    7,
    5,
    2,
    6,
    7,
    6,
    2,
    7,
    7,
    7,
    2,
    8,
    7,
    8,
    2,
    9,
    7,
    9,
    2,
    10,
    7,
    10,
    2,
    11,
    7,
    11,
    2,
    12,
    7,
    12,
    2,
    13,
    7,
    13,
    2,
    14,
    7,
    14,
    2,
    15,
    7,
    15,
    2,
    16,
    7,
    16,
    2,
    17,
    7,
    17,
    2,
    18,
    7,
    18,
    2,
    19,
    7,
    19,
    2,
    20,
    7,
    20,
    2,
    21,
    7,
    21,
    2,
    22,
    7,
    22,
    2,
    23,
    7,
    23,
    2,
    24,
    7,
    24,
    2,
    25,
    7,
    25,
    2,
    26,
    7,
    26,
    2,
    27,
    7,
    27,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    1,
    5,
    1,
    61,
    8,
    1,
    10,
    1,
    12,
    1,
    64,
    9,
    1,
    1,
    2,
    1,
    2,
    1,
    2,
    1,
    2,
    1,
    2,
    1,
    2,
    1,
    2,
    3,
    2,
    73,
    8,
    2,
    1,
    3,
    1,
    3,
    1,
    4,
    1,
    4,
    1,
    5,
    1,
    5,
    1,
    5,
    1,
    5,
    1,
    5,
    1,
    5,
    1,
    6,
    1,
    6,
    1,
    6,
    5,
    6,
    88,
    8,
    6,
    10,
    6,
    12,
    6,
    91,
    9,
    6,
    1,
    6,
    3,
    6,
    94,
    8,
    6,
    1,
    6,
    1,
    6,
    1,
    7,
    1,
    7,
    1,
    7,
    3,
    7,
    101,
    8,
    7,
    1,
    7,
    1,
    7,
    1,
    7,
    1,
    7,
    1,
    7,
    3,
    7,
    108,
    8,
    7,
    1,
    7,
    1,
    7,
    3,
    7,
    112,
    8,
    7,
    1,
    8,
    1,
    8,
    1,
    8,
    5,
    8,
    117,
    8,
    8,
    10,
    8,
    12,
    8,
    120,
    9,
    8,
    1,
    8,
    3,
    8,
    123,
    8,
    8,
    1,
    8,
    3,
    8,
    126,
    8,
    8,
    1,
    8,
    1,
    8,
    1,
    9,
    1,
    9,
    1,
    9,
    5,
    9,
    133,
    8,
    9,
    10,
    9,
    12,
    9,
    136,
    9,
    9,
    1,
    9,
    3,
    9,
    139,
    8,
    9,
    1,
    9,
    3,
    9,
    142,
    8,
    9,
    1,
    9,
    1,
    9,
    1,
    10,
    1,
    10,
    1,
    10,
    5,
    10,
    149,
    8,
    10,
    10,
    10,
    12,
    10,
    152,
    9,
    10,
    1,
    10,
    3,
    10,
    155,
    8,
    10,
    1,
    10,
    3,
    10,
    158,
    8,
    10,
    1,
    10,
    1,
    10,
    1,
    11,
    1,
    11,
    1,
    11,
    1,
    12,
    1,
    12,
    1,
    12,
    3,
    12,
    168,
    8,
    12,
    1,
    12,
    3,
    12,
    171,
    8,
    12,
    1,
    13,
    1,
    13,
    1,
    13,
    1,
    13,
    1,
    14,
    1,
    14,
    1,
    14,
    5,
    14,
    180,
    8,
    14,
    10,
    14,
    12,
    14,
    183,
    9,
    14,
    1,
    14,
    3,
    14,
    186,
    8,
    14,
    1,
    14,
    1,
    14,
    1,
    14,
    1,
    14,
    1,
    14,
    5,
    14,
    193,
    8,
    14,
    10,
    14,
    12,
    14,
    196,
    9,
    14,
    1,
    14,
    3,
    14,
    199,
    8,
    14,
    1,
    14,
    1,
    14,
    3,
    14,
    203,
    8,
    14,
    1,
    15,
    1,
    15,
    1,
    15,
    5,
    15,
    208,
    8,
    15,
    10,
    15,
    12,
    15,
    211,
    9,
    15,
    1,
    15,
    3,
    15,
    214,
    8,
    15,
    1,
    15,
    1,
    15,
    1,
    16,
    1,
    16,
    1,
    16,
    1,
    16,
    1,
    17,
    1,
    17,
    1,
    17,
    5,
    17,
    225,
    8,
    17,
    10,
    17,
    12,
    17,
    228,
    9,
    17,
    1,
    17,
    3,
    17,
    231,
    8,
    17,
    1,
    17,
    1,
    17,
    1,
    18,
    1,
    18,
    3,
    18,
    237,
    8,
    18,
    1,
    19,
    1,
    19,
    1,
    19,
    5,
    19,
    242,
    8,
    19,
    10,
    19,
    12,
    19,
    245,
    9,
    19,
    1,
    19,
    3,
    19,
    248,
    8,
    19,
    1,
    19,
    1,
    19,
    1,
    20,
    4,
    20,
    253,
    8,
    20,
    11,
    20,
    12,
    20,
    254,
    1,
    21,
    1,
    21,
    1,
    21,
    1,
    21,
    1,
    22,
    1,
    22,
    4,
    22,
    263,
    8,
    22,
    11,
    22,
    12,
    22,
    264,
    1,
    22,
    1,
    22,
    1,
    23,
    1,
    23,
    1,
    23,
    1,
    23,
    1,
    23,
    1,
    23,
    1,
    23,
    3,
    23,
    276,
    8,
    23,
    1,
    24,
    1,
    24,
    3,
    24,
    280,
    8,
    24,
    1,
    25,
    1,
    25,
    1,
    25,
    1,
    26,
    1,
    26,
    1,
    27,
    1,
    27,
    1,
    27,
    5,
    27,
    290,
    8,
    27,
    10,
    27,
    12,
    27,
    293,
    9,
    27,
    1,
    27,
    0,
    0,
    28,
    0,
    2,
    4,
    6,
    8,
    10,
    12,
    14,
    16,
    18,
    20,
    22,
    24,
    26,
    28,
    30,
    32,
    34,
    36,
    38,
    40,
    42,
    44,
    46,
    48,
    50,
    52,
    54,
    0,
    0,
    311,
    0,
    56,
    1,
    0,
    0,
    0,
    2,
    62,
    1,
    0,
    0,
    0,
    4,
    72,
    1,
    0,
    0,
    0,
    6,
    74,
    1,
    0,
    0,
    0,
    8,
    76,
    1,
    0,
    0,
    0,
    10,
    78,
    1,
    0,
    0,
    0,
    12,
    84,
    1,
    0,
    0,
    0,
    14,
    111,
    1,
    0,
    0,
    0,
    16,
    113,
    1,
    0,
    0,
    0,
    18,
    129,
    1,
    0,
    0,
    0,
    20,
    145,
    1,
    0,
    0,
    0,
    22,
    161,
    1,
    0,
    0,
    0,
    24,
    170,
    1,
    0,
    0,
    0,
    26,
    172,
    1,
    0,
    0,
    0,
    28,
    202,
    1,
    0,
    0,
    0,
    30,
    204,
    1,
    0,
    0,
    0,
    32,
    217,
    1,
    0,
    0,
    0,
    34,
    221,
    1,
    0,
    0,
    0,
    36,
    236,
    1,
    0,
    0,
    0,
    38,
    238,
    1,
    0,
    0,
    0,
    40,
    252,
    1,
    0,
    0,
    0,
    42,
    256,
    1,
    0,
    0,
    0,
    44,
    260,
    1,
    0,
    0,
    0,
    46,
    275,
    1,
    0,
    0,
    0,
    48,
    279,
    1,
    0,
    0,
    0,
    50,
    281,
    1,
    0,
    0,
    0,
    52,
    284,
    1,
    0,
    0,
    0,
    54,
    286,
    1,
    0,
    0,
    0,
    56,
    57,
    3,
    2,
    1,
    0,
    57,
    58,
    5,
    0,
    0,
    1,
    58,
    1,
    1,
    0,
    0,
    0,
    59,
    61,
    3,
    4,
    2,
    0,
    60,
    59,
    1,
    0,
    0,
    0,
    61,
    64,
    1,
    0,
    0,
    0,
    62,
    60,
    1,
    0,
    0,
    0,
    62,
    63,
    1,
    0,
    0,
    0,
    63,
    3,
    1,
    0,
    0,
    0,
    64,
    62,
    1,
    0,
    0,
    0,
    65,
    73,
    3,
    28,
    14,
    0,
    66,
    73,
    3,
    14,
    7,
    0,
    67,
    73,
    3,
    10,
    5,
    0,
    68,
    73,
    3,
    30,
    15,
    0,
    69,
    73,
    3,
    32,
    16,
    0,
    70,
    73,
    3,
    6,
    3,
    0,
    71,
    73,
    3,
    8,
    4,
    0,
    72,
    65,
    1,
    0,
    0,
    0,
    72,
    66,
    1,
    0,
    0,
    0,
    72,
    67,
    1,
    0,
    0,
    0,
    72,
    68,
    1,
    0,
    0,
    0,
    72,
    69,
    1,
    0,
    0,
    0,
    72,
    70,
    1,
    0,
    0,
    0,
    72,
    71,
    1,
    0,
    0,
    0,
    73,
    5,
    1,
    0,
    0,
    0,
    74,
    75,
    5,
    13,
    0,
    0,
    75,
    7,
    1,
    0,
    0,
    0,
    76,
    77,
    5,
    11,
    0,
    0,
    77,
    9,
    1,
    0,
    0,
    0,
    78,
    79,
    3,
    12,
    6,
    0,
    79,
    80,
    3,
    2,
    1,
    0,
    80,
    81,
    5,
    2,
    0,
    0,
    81,
    82,
    3,
    46,
    23,
    0,
    82,
    83,
    5,
    14,
    0,
    0,
    83,
    11,
    1,
    0,
    0,
    0,
    84,
    85,
    5,
    1,
    0,
    0,
    85,
    89,
    3,
    46,
    23,
    0,
    86,
    88,
    3,
    36,
    18,
    0,
    87,
    86,
    1,
    0,
    0,
    0,
    88,
    91,
    1,
    0,
    0,
    0,
    89,
    87,
    1,
    0,
    0,
    0,
    89,
    90,
    1,
    0,
    0,
    0,
    90,
    93,
    1,
    0,
    0,
    0,
    91,
    89,
    1,
    0,
    0,
    0,
    92,
    94,
    3,
    40,
    20,
    0,
    93,
    92,
    1,
    0,
    0,
    0,
    93,
    94,
    1,
    0,
    0,
    0,
    94,
    95,
    1,
    0,
    0,
    0,
    95,
    96,
    5,
    14,
    0,
    0,
    96,
    13,
    1,
    0,
    0,
    0,
    97,
    98,
    3,
    16,
    8,
    0,
    98,
    100,
    3,
    2,
    1,
    0,
    99,
    101,
    3,
    24,
    12,
    0,
    100,
    99,
    1,
    0,
    0,
    0,
    100,
    101,
    1,
    0,
    0,
    0,
    101,
    102,
    1,
    0,
    0,
    0,
    102,
    103,
    3,
    26,
    13,
    0,
    103,
    112,
    1,
    0,
    0,
    0,
    104,
    105,
    3,
    18,
    9,
    0,
    105,
    107,
    3,
    2,
    1,
    0,
    106,
    108,
    3,
    22,
    11,
    0,
    107,
    106,
    1,
    0,
    0,
    0,
    107,
    108,
    1,
    0,
    0,
    0,
    108,
    109,
    1,
    0,
    0,
    0,
    109,
    110,
    3,
    26,
    13,
    0,
    110,
    112,
    1,
    0,
    0,
    0,
    111,
    97,
    1,
    0,
    0,
    0,
    111,
    104,
    1,
    0,
    0,
    0,
    112,
    15,
    1,
    0,
    0,
    0,
    113,
    114,
    5,
    5,
    0,
    0,
    114,
    118,
    3,
    46,
    23,
    0,
    115,
    117,
    3,
    36,
    18,
    0,
    116,
    115,
    1,
    0,
    0,
    0,
    117,
    120,
    1,
    0,
    0,
    0,
    118,
    116,
    1,
    0,
    0,
    0,
    118,
    119,
    1,
    0,
    0,
    0,
    119,
    122,
    1,
    0,
    0,
    0,
    120,
    118,
    1,
    0,
    0,
    0,
    121,
    123,
    3,
    40,
    20,
    0,
    122,
    121,
    1,
    0,
    0,
    0,
    122,
    123,
    1,
    0,
    0,
    0,
    123,
    125,
    1,
    0,
    0,
    0,
    124,
    126,
    3,
    44,
    22,
    0,
    125,
    124,
    1,
    0,
    0,
    0,
    125,
    126,
    1,
    0,
    0,
    0,
    126,
    127,
    1,
    0,
    0,
    0,
    127,
    128,
    5,
    16,
    0,
    0,
    128,
    17,
    1,
    0,
    0,
    0,
    129,
    130,
    5,
    8,
    0,
    0,
    130,
    134,
    3,
    46,
    23,
    0,
    131,
    133,
    3,
    36,
    18,
    0,
    132,
    131,
    1,
    0,
    0,
    0,
    133,
    136,
    1,
    0,
    0,
    0,
    134,
    132,
    1,
    0,
    0,
    0,
    134,
    135,
    1,
    0,
    0,
    0,
    135,
    138,
    1,
    0,
    0,
    0,
    136,
    134,
    1,
    0,
    0,
    0,
    137,
    139,
    3,
    40,
    20,
    0,
    138,
    137,
    1,
    0,
    0,
    0,
    138,
    139,
    1,
    0,
    0,
    0,
    139,
    141,
    1,
    0,
    0,
    0,
    140,
    142,
    3,
    44,
    22,
    0,
    141,
    140,
    1,
    0,
    0,
    0,
    141,
    142,
    1,
    0,
    0,
    0,
    142,
    143,
    1,
    0,
    0,
    0,
    143,
    144,
    5,
    16,
    0,
    0,
    144,
    19,
    1,
    0,
    0,
    0,
    145,
    146,
    5,
    9,
    0,
    0,
    146,
    150,
    3,
    46,
    23,
    0,
    147,
    149,
    3,
    36,
    18,
    0,
    148,
    147,
    1,
    0,
    0,
    0,
    149,
    152,
    1,
    0,
    0,
    0,
    150,
    148,
    1,
    0,
    0,
    0,
    150,
    151,
    1,
    0,
    0,
    0,
    151,
    154,
    1,
    0,
    0,
    0,
    152,
    150,
    1,
    0,
    0,
    0,
    153,
    155,
    3,
    40,
    20,
    0,
    154,
    153,
    1,
    0,
    0,
    0,
    154,
    155,
    1,
    0,
    0,
    0,
    155,
    157,
    1,
    0,
    0,
    0,
    156,
    158,
    3,
    44,
    22,
    0,
    157,
    156,
    1,
    0,
    0,
    0,
    157,
    158,
    1,
    0,
    0,
    0,
    158,
    159,
    1,
    0,
    0,
    0,
    159,
    160,
    5,
    16,
    0,
    0,
    160,
    21,
    1,
    0,
    0,
    0,
    161,
    162,
    5,
    7,
    0,
    0,
    162,
    163,
    3,
    2,
    1,
    0,
    163,
    23,
    1,
    0,
    0,
    0,
    164,
    165,
    3,
    20,
    10,
    0,
    165,
    167,
    3,
    2,
    1,
    0,
    166,
    168,
    3,
    24,
    12,
    0,
    167,
    166,
    1,
    0,
    0,
    0,
    167,
    168,
    1,
    0,
    0,
    0,
    168,
    171,
    1,
    0,
    0,
    0,
    169,
    171,
    3,
    22,
    11,
    0,
    170,
    164,
    1,
    0,
    0,
    0,
    170,
    169,
    1,
    0,
    0,
    0,
    171,
    25,
    1,
    0,
    0,
    0,
    172,
    173,
    5,
    6,
    0,
    0,
    173,
    174,
    3,
    46,
    23,
    0,
    174,
    175,
    5,
    16,
    0,
    0,
    175,
    27,
    1,
    0,
    0,
    0,
    176,
    177,
    5,
    12,
    0,
    0,
    177,
    181,
    3,
    46,
    23,
    0,
    178,
    180,
    3,
    36,
    18,
    0,
    179,
    178,
    1,
    0,
    0,
    0,
    180,
    183,
    1,
    0,
    0,
    0,
    181,
    179,
    1,
    0,
    0,
    0,
    181,
    182,
    1,
    0,
    0,
    0,
    182,
    185,
    1,
    0,
    0,
    0,
    183,
    181,
    1,
    0,
    0,
    0,
    184,
    186,
    3,
    40,
    20,
    0,
    185,
    184,
    1,
    0,
    0,
    0,
    185,
    186,
    1,
    0,
    0,
    0,
    186,
    187,
    1,
    0,
    0,
    0,
    187,
    188,
    5,
    16,
    0,
    0,
    188,
    203,
    1,
    0,
    0,
    0,
    189,
    190,
    5,
    3,
    0,
    0,
    190,
    194,
    3,
    46,
    23,
    0,
    191,
    193,
    3,
    36,
    18,
    0,
    192,
    191,
    1,
    0,
    0,
    0,
    193,
    196,
    1,
    0,
    0,
    0,
    194,
    192,
    1,
    0,
    0,
    0,
    194,
    195,
    1,
    0,
    0,
    0,
    195,
    198,
    1,
    0,
    0,
    0,
    196,
    194,
    1,
    0,
    0,
    0,
    197,
    199,
    3,
    40,
    20,
    0,
    198,
    197,
    1,
    0,
    0,
    0,
    198,
    199,
    1,
    0,
    0,
    0,
    199,
    200,
    1,
    0,
    0,
    0,
    200,
    201,
    5,
    15,
    0,
    0,
    201,
    203,
    1,
    0,
    0,
    0,
    202,
    176,
    1,
    0,
    0,
    0,
    202,
    189,
    1,
    0,
    0,
    0,
    203,
    29,
    1,
    0,
    0,
    0,
    204,
    205,
    5,
    10,
    0,
    0,
    205,
    209,
    3,
    48,
    24,
    0,
    206,
    208,
    3,
    36,
    18,
    0,
    207,
    206,
    1,
    0,
    0,
    0,
    208,
    211,
    1,
    0,
    0,
    0,
    209,
    207,
    1,
    0,
    0,
    0,
    209,
    210,
    1,
    0,
    0,
    0,
    210,
    213,
    1,
    0,
    0,
    0,
    211,
    209,
    1,
    0,
    0,
    0,
    212,
    214,
    3,
    40,
    20,
    0,
    213,
    212,
    1,
    0,
    0,
    0,
    213,
    214,
    1,
    0,
    0,
    0,
    214,
    215,
    1,
    0,
    0,
    0,
    215,
    216,
    5,
    16,
    0,
    0,
    216,
    31,
    1,
    0,
    0,
    0,
    217,
    218,
    3,
    34,
    17,
    0,
    218,
    219,
    3,
    2,
    1,
    0,
    219,
    220,
    3,
    26,
    13,
    0,
    220,
    33,
    1,
    0,
    0,
    0,
    221,
    222,
    5,
    4,
    0,
    0,
    222,
    226,
    3,
    48,
    24,
    0,
    223,
    225,
    3,
    36,
    18,
    0,
    224,
    223,
    1,
    0,
    0,
    0,
    225,
    228,
    1,
    0,
    0,
    0,
    226,
    224,
    1,
    0,
    0,
    0,
    226,
    227,
    1,
    0,
    0,
    0,
    227,
    230,
    1,
    0,
    0,
    0,
    228,
    226,
    1,
    0,
    0,
    0,
    229,
    231,
    3,
    40,
    20,
    0,
    230,
    229,
    1,
    0,
    0,
    0,
    230,
    231,
    1,
    0,
    0,
    0,
    231,
    232,
    1,
    0,
    0,
    0,
    232,
    233,
    5,
    16,
    0,
    0,
    233,
    35,
    1,
    0,
    0,
    0,
    234,
    237,
    3,
    46,
    23,
    0,
    235,
    237,
    3,
    38,
    19,
    0,
    236,
    234,
    1,
    0,
    0,
    0,
    236,
    235,
    1,
    0,
    0,
    0,
    237,
    37,
    1,
    0,
    0,
    0,
    238,
    239,
    5,
    17,
    0,
    0,
    239,
    243,
    3,
    46,
    23,
    0,
    240,
    242,
    3,
    36,
    18,
    0,
    241,
    240,
    1,
    0,
    0,
    0,
    242,
    245,
    1,
    0,
    0,
    0,
    243,
    241,
    1,
    0,
    0,
    0,
    243,
    244,
    1,
    0,
    0,
    0,
    244,
    247,
    1,
    0,
    0,
    0,
    245,
    243,
    1,
    0,
    0,
    0,
    246,
    248,
    3,
    40,
    20,
    0,
    247,
    246,
    1,
    0,
    0,
    0,
    247,
    248,
    1,
    0,
    0,
    0,
    248,
    249,
    1,
    0,
    0,
    0,
    249,
    250,
    5,
    18,
    0,
    0,
    250,
    39,
    1,
    0,
    0,
    0,
    251,
    253,
    3,
    42,
    21,
    0,
    252,
    251,
    1,
    0,
    0,
    0,
    253,
    254,
    1,
    0,
    0,
    0,
    254,
    252,
    1,
    0,
    0,
    0,
    254,
    255,
    1,
    0,
    0,
    0,
    255,
    41,
    1,
    0,
    0,
    0,
    256,
    257,
    5,
    29,
    0,
    0,
    257,
    258,
    5,
    22,
    0,
    0,
    258,
    259,
    3,
    36,
    18,
    0,
    259,
    43,
    1,
    0,
    0,
    0,
    260,
    262,
    5,
    19,
    0,
    0,
    261,
    263,
    5,
    29,
    0,
    0,
    262,
    261,
    1,
    0,
    0,
    0,
    263,
    264,
    1,
    0,
    0,
    0,
    264,
    262,
    1,
    0,
    0,
    0,
    264,
    265,
    1,
    0,
    0,
    0,
    265,
    266,
    1,
    0,
    0,
    0,
    266,
    267,
    5,
    20,
    0,
    0,
    267,
    45,
    1,
    0,
    0,
    0,
    268,
    276,
    3,
    52,
    26,
    0,
    269,
    276,
    3,
    50,
    25,
    0,
    270,
    276,
    5,
    23,
    0,
    0,
    271,
    276,
    5,
    24,
    0,
    0,
    272,
    276,
    5,
    25,
    0,
    0,
    273,
    276,
    5,
    26,
    0,
    0,
    274,
    276,
    5,
    27,
    0,
    0,
    275,
    268,
    1,
    0,
    0,
    0,
    275,
    269,
    1,
    0,
    0,
    0,
    275,
    270,
    1,
    0,
    0,
    0,
    275,
    271,
    1,
    0,
    0,
    0,
    275,
    272,
    1,
    0,
    0,
    0,
    275,
    273,
    1,
    0,
    0,
    0,
    275,
    274,
    1,
    0,
    0,
    0,
    276,
    47,
    1,
    0,
    0,
    0,
    277,
    280,
    3,
    46,
    23,
    0,
    278,
    280,
    3,
    38,
    19,
    0,
    279,
    277,
    1,
    0,
    0,
    0,
    279,
    278,
    1,
    0,
    0,
    0,
    280,
    49,
    1,
    0,
    0,
    0,
    281,
    282,
    5,
    28,
    0,
    0,
    282,
    283,
    3,
    54,
    27,
    0,
    283,
    51,
    1,
    0,
    0,
    0,
    284,
    285,
    3,
    54,
    27,
    0,
    285,
    53,
    1,
    0,
    0,
    0,
    286,
    291,
    5,
    29,
    0,
    0,
    287,
    288,
    5,
    21,
    0,
    0,
    288,
    290,
    5,
    29,
    0,
    0,
    289,
    287,
    1,
    0,
    0,
    0,
    290,
    293,
    1,
    0,
    0,
    0,
    291,
    289,
    1,
    0,
    0,
    0,
    291,
    292,
    1,
    0,
    0,
    0,
    292,
    55,
    1,
    0,
    0,
    0,
    293,
    291,
    1,
    0,
    0,
    0,
    35,
    62,
    72,
    89,
    93,
    100,
    107,
    111,
    118,
    122,
    125,
    134,
    138,
    141,
    150,
    154,
    157,
    167,
    170,
    181,
    185,
    194,
    198,
    202,
    209,
    213,
    226,
    230,
    236,
    243,
    247,
    254,
    264,
    275,
    279,
    291,
  ];

  static final ATN _ATN = ATNDeserializer().deserialize(_serializedATN);
}

class RootContext extends ParserRuleContext {
  RootContext([ParserRuleContext? super.parent, super.invokingState]);
  ProgramContext? program() => getRuleContext<ProgramContext>(0);
  TerminalNode? EOF() => getToken(HandlebarsParser.TOKEN_EOF, 0);
  @override
  int get ruleIndex => RULE_root;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitRoot(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class ProgramContext extends ParserRuleContext {
  ProgramContext([ParserRuleContext? super.parent, super.invokingState]);
  List<StatementContext> statements() => getRuleContexts<StatementContext>();
  StatementContext? statement(int i) => getRuleContext<StatementContext>(i);
  @override
  int get ruleIndex => RULE_program;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitProgram(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class StatementContext extends ParserRuleContext {
  StatementContext([ParserRuleContext? super.parent, super.invokingState]);
  MustacheContext? mustache() => getRuleContext<MustacheContext>(0);
  BlockContext? block() => getRuleContext<BlockContext>(0);
  RawBlockContext? rawBlock() => getRuleContext<RawBlockContext>(0);
  PartialContext? partial() => getRuleContext<PartialContext>(0);
  PartialBlockContext? partialBlock() => getRuleContext<PartialBlockContext>(0);
  ContentContext? content() => getRuleContext<ContentContext>(0);
  CommentContext? comment() => getRuleContext<CommentContext>(0);
  @override
  int get ruleIndex => RULE_statement;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitStatement(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class ContentContext extends ParserRuleContext {
  ContentContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? CONTENT() => getToken(HandlebarsParser.TOKEN_CONTENT, 0);
  @override
  int get ruleIndex => RULE_content;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitContent(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class CommentContext extends ParserRuleContext {
  CommentContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? COMMENT() => getToken(HandlebarsParser.TOKEN_COMMENT, 0);
  @override
  int get ruleIndex => RULE_comment;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitComment(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class RawBlockContext extends ParserRuleContext {
  RawBlockContext([ParserRuleContext? super.parent, super.invokingState]);
  OpenRawBlockContext? openRawBlock() => getRuleContext<OpenRawBlockContext>(0);
  ProgramContext? program() => getRuleContext<ProgramContext>(0);
  TerminalNode? END_RAW_BLOCK() => getToken(HandlebarsParser.TOKEN_END_RAW_BLOCK, 0);
  HelperNameContext? helperName() => getRuleContext<HelperNameContext>(0);
  TerminalNode? CLOSE_RAW_BLOCK() => getToken(HandlebarsParser.TOKEN_CLOSE_RAW_BLOCK, 0);
  @override
  int get ruleIndex => RULE_rawBlock;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitRawBlock(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class OpenRawBlockContext extends ParserRuleContext {
  OpenRawBlockContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? OPEN_RAW_BLOCK() => getToken(HandlebarsParser.TOKEN_OPEN_RAW_BLOCK, 0);
  HelperNameContext? helperName() => getRuleContext<HelperNameContext>(0);
  TerminalNode? CLOSE_RAW_BLOCK() => getToken(HandlebarsParser.TOKEN_CLOSE_RAW_BLOCK, 0);
  List<ParamContext> params() => getRuleContexts<ParamContext>();
  ParamContext? param(int i) => getRuleContext<ParamContext>(i);
  HashContext? hash() => getRuleContext<HashContext>(0);
  @override
  int get ruleIndex => RULE_openRawBlock;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitOpenRawBlock(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class BlockContext extends ParserRuleContext {
  BlockContext([ParserRuleContext? super.parent, super.invokingState]);
  OpenBlockContext? openBlock() => getRuleContext<OpenBlockContext>(0);
  ProgramContext? program() => getRuleContext<ProgramContext>(0);
  CloseBlockContext? closeBlock() => getRuleContext<CloseBlockContext>(0);
  InverseChainContext? inverseChain() => getRuleContext<InverseChainContext>(0);
  OpenInverseContext? openInverse() => getRuleContext<OpenInverseContext>(0);
  InverseAndProgramContext? inverseAndProgram() => getRuleContext<InverseAndProgramContext>(0);
  @override
  int get ruleIndex => RULE_block;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitBlock(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class OpenBlockContext extends ParserRuleContext {
  OpenBlockContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? OPEN_BLOCK() => getToken(HandlebarsParser.TOKEN_OPEN_BLOCK, 0);
  HelperNameContext? helperName() => getRuleContext<HelperNameContext>(0);
  TerminalNode? CLOSE() => getToken(HandlebarsParser.TOKEN_CLOSE, 0);
  List<ParamContext> params() => getRuleContexts<ParamContext>();
  ParamContext? param(int i) => getRuleContext<ParamContext>(i);
  HashContext? hash() => getRuleContext<HashContext>(0);
  BlockParamsContext? blockParams() => getRuleContext<BlockParamsContext>(0);
  @override
  int get ruleIndex => RULE_openBlock;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitOpenBlock(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class OpenInverseContext extends ParserRuleContext {
  OpenInverseContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? OPEN_INVERSE() => getToken(HandlebarsParser.TOKEN_OPEN_INVERSE, 0);
  HelperNameContext? helperName() => getRuleContext<HelperNameContext>(0);
  TerminalNode? CLOSE() => getToken(HandlebarsParser.TOKEN_CLOSE, 0);
  List<ParamContext> params() => getRuleContexts<ParamContext>();
  ParamContext? param(int i) => getRuleContext<ParamContext>(i);
  HashContext? hash() => getRuleContext<HashContext>(0);
  BlockParamsContext? blockParams() => getRuleContext<BlockParamsContext>(0);
  @override
  int get ruleIndex => RULE_openInverse;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitOpenInverse(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class OpenInverseChainContext extends ParserRuleContext {
  OpenInverseChainContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? OPEN_INVERSE_CHAIN() => getToken(HandlebarsParser.TOKEN_OPEN_INVERSE_CHAIN, 0);
  HelperNameContext? helperName() => getRuleContext<HelperNameContext>(0);
  TerminalNode? CLOSE() => getToken(HandlebarsParser.TOKEN_CLOSE, 0);
  List<ParamContext> params() => getRuleContexts<ParamContext>();
  ParamContext? param(int i) => getRuleContext<ParamContext>(i);
  HashContext? hash() => getRuleContext<HashContext>(0);
  BlockParamsContext? blockParams() => getRuleContext<BlockParamsContext>(0);
  @override
  int get ruleIndex => RULE_openInverseChain;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitOpenInverseChain(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class InverseAndProgramContext extends ParserRuleContext {
  InverseAndProgramContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? INVERSE() => getToken(HandlebarsParser.TOKEN_INVERSE, 0);
  ProgramContext? program() => getRuleContext<ProgramContext>(0);
  @override
  int get ruleIndex => RULE_inverseAndProgram;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitInverseAndProgram(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class InverseChainContext extends ParserRuleContext {
  InverseChainContext([ParserRuleContext? super.parent, super.invokingState]);
  OpenInverseChainContext? openInverseChain() => getRuleContext<OpenInverseChainContext>(0);
  ProgramContext? program() => getRuleContext<ProgramContext>(0);
  InverseChainContext? inverseChain() => getRuleContext<InverseChainContext>(0);
  InverseAndProgramContext? inverseAndProgram() => getRuleContext<InverseAndProgramContext>(0);
  @override
  int get ruleIndex => RULE_inverseChain;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitInverseChain(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class CloseBlockContext extends ParserRuleContext {
  CloseBlockContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? OPEN_ENDBLOCK() => getToken(HandlebarsParser.TOKEN_OPEN_ENDBLOCK, 0);
  HelperNameContext? helperName() => getRuleContext<HelperNameContext>(0);
  TerminalNode? CLOSE() => getToken(HandlebarsParser.TOKEN_CLOSE, 0);
  @override
  int get ruleIndex => RULE_closeBlock;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitCloseBlock(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class MustacheContext extends ParserRuleContext {
  MustacheContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? OPEN() => getToken(HandlebarsParser.TOKEN_OPEN, 0);
  HelperNameContext? helperName() => getRuleContext<HelperNameContext>(0);
  TerminalNode? CLOSE() => getToken(HandlebarsParser.TOKEN_CLOSE, 0);
  List<ParamContext> params() => getRuleContexts<ParamContext>();
  ParamContext? param(int i) => getRuleContext<ParamContext>(i);
  HashContext? hash() => getRuleContext<HashContext>(0);
  TerminalNode? OPEN_UNESCAPED() => getToken(HandlebarsParser.TOKEN_OPEN_UNESCAPED, 0);
  TerminalNode? CLOSE_UNESCAPED() => getToken(HandlebarsParser.TOKEN_CLOSE_UNESCAPED, 0);
  @override
  int get ruleIndex => RULE_mustache;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitMustache(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class PartialContext extends ParserRuleContext {
  PartialContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? OPEN_PARTIAL() => getToken(HandlebarsParser.TOKEN_OPEN_PARTIAL, 0);
  PartialNameContext? partialName() => getRuleContext<PartialNameContext>(0);
  TerminalNode? CLOSE() => getToken(HandlebarsParser.TOKEN_CLOSE, 0);
  List<ParamContext> params() => getRuleContexts<ParamContext>();
  ParamContext? param(int i) => getRuleContext<ParamContext>(i);
  HashContext? hash() => getRuleContext<HashContext>(0);
  @override
  int get ruleIndex => RULE_partial;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitPartial(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class PartialBlockContext extends ParserRuleContext {
  PartialBlockContext([ParserRuleContext? super.parent, super.invokingState]);
  OpenPartialBlockContext? openPartialBlock() => getRuleContext<OpenPartialBlockContext>(0);
  ProgramContext? program() => getRuleContext<ProgramContext>(0);
  CloseBlockContext? closeBlock() => getRuleContext<CloseBlockContext>(0);
  @override
  int get ruleIndex => RULE_partialBlock;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitPartialBlock(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class OpenPartialBlockContext extends ParserRuleContext {
  OpenPartialBlockContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? OPEN_PARTIAL_BLOCK() => getToken(HandlebarsParser.TOKEN_OPEN_PARTIAL_BLOCK, 0);
  PartialNameContext? partialName() => getRuleContext<PartialNameContext>(0);
  TerminalNode? CLOSE() => getToken(HandlebarsParser.TOKEN_CLOSE, 0);
  List<ParamContext> params() => getRuleContexts<ParamContext>();
  ParamContext? param(int i) => getRuleContext<ParamContext>(i);
  HashContext? hash() => getRuleContext<HashContext>(0);
  @override
  int get ruleIndex => RULE_openPartialBlock;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitOpenPartialBlock(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class ParamContext extends ParserRuleContext {
  ParamContext([ParserRuleContext? super.parent, super.invokingState]);
  HelperNameContext? helperName() => getRuleContext<HelperNameContext>(0);
  SexprContext? sexpr() => getRuleContext<SexprContext>(0);
  @override
  int get ruleIndex => RULE_param;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitParam(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class SexprContext extends ParserRuleContext {
  SexprContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? OPEN_SEXPR() => getToken(HandlebarsParser.TOKEN_OPEN_SEXPR, 0);
  HelperNameContext? helperName() => getRuleContext<HelperNameContext>(0);
  TerminalNode? CLOSE_SEXPR() => getToken(HandlebarsParser.TOKEN_CLOSE_SEXPR, 0);
  List<ParamContext> params() => getRuleContexts<ParamContext>();
  ParamContext? param(int i) => getRuleContext<ParamContext>(i);
  HashContext? hash() => getRuleContext<HashContext>(0);
  @override
  int get ruleIndex => RULE_sexpr;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitSexpr(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class HashContext extends ParserRuleContext {
  HashContext([ParserRuleContext? super.parent, super.invokingState]);
  List<HashSegmentContext> hashSegments() => getRuleContexts<HashSegmentContext>();
  HashSegmentContext? hashSegment(int i) => getRuleContext<HashSegmentContext>(i);
  @override
  int get ruleIndex => RULE_hash;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitHash(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class HashSegmentContext extends ParserRuleContext {
  HashSegmentContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? ID() => getToken(HandlebarsParser.TOKEN_ID, 0);
  TerminalNode? EQUALS() => getToken(HandlebarsParser.TOKEN_EQUALS, 0);
  ParamContext? param() => getRuleContext<ParamContext>(0);
  @override
  int get ruleIndex => RULE_hashSegment;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitHashSegment(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class BlockParamsContext extends ParserRuleContext {
  BlockParamsContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? OPEN_BLOCK_PARAMS() => getToken(HandlebarsParser.TOKEN_OPEN_BLOCK_PARAMS, 0);
  TerminalNode? CLOSE_BLOCK_PARAMS() => getToken(HandlebarsParser.TOKEN_CLOSE_BLOCK_PARAMS, 0);
  List<TerminalNode> IDs() => getTokens(HandlebarsParser.TOKEN_ID);
  TerminalNode? ID(int i) => getToken(HandlebarsParser.TOKEN_ID, i);
  @override
  int get ruleIndex => RULE_blockParams;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitBlockParams(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class HelperNameContext extends ParserRuleContext {
  HelperNameContext([ParserRuleContext? super.parent, super.invokingState]);
  PathContext? path() => getRuleContext<PathContext>(0);
  DataNameContext? dataName() => getRuleContext<DataNameContext>(0);
  TerminalNode? STRING() => getToken(HandlebarsParser.TOKEN_STRING, 0);
  TerminalNode? NUMBER() => getToken(HandlebarsParser.TOKEN_NUMBER, 0);
  TerminalNode? BOOLEAN() => getToken(HandlebarsParser.TOKEN_BOOLEAN, 0);
  TerminalNode? UNDEFINED() => getToken(HandlebarsParser.TOKEN_UNDEFINED, 0);
  TerminalNode? NULL_LIT() => getToken(HandlebarsParser.TOKEN_NULL_LIT, 0);
  @override
  int get ruleIndex => RULE_helperName;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitHelperName(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class PartialNameContext extends ParserRuleContext {
  PartialNameContext([ParserRuleContext? super.parent, super.invokingState]);
  HelperNameContext? helperName() => getRuleContext<HelperNameContext>(0);
  SexprContext? sexpr() => getRuleContext<SexprContext>(0);
  @override
  int get ruleIndex => RULE_partialName;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitPartialName(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class DataNameContext extends ParserRuleContext {
  DataNameContext([ParserRuleContext? super.parent, super.invokingState]);
  TerminalNode? DATA() => getToken(HandlebarsParser.TOKEN_DATA, 0);
  PathSegmentsContext? pathSegments() => getRuleContext<PathSegmentsContext>(0);
  @override
  int get ruleIndex => RULE_dataName;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitDataName(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class PathContext extends ParserRuleContext {
  PathContext([ParserRuleContext? super.parent, super.invokingState]);
  PathSegmentsContext? pathSegments() => getRuleContext<PathSegmentsContext>(0);
  @override
  int get ruleIndex => RULE_path;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitPath(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}

class PathSegmentsContext extends ParserRuleContext {
  PathSegmentsContext([ParserRuleContext? super.parent, super.invokingState]);
  List<TerminalNode> IDs() => getTokens(HandlebarsParser.TOKEN_ID);
  TerminalNode? ID(int i) => getToken(HandlebarsParser.TOKEN_ID, i);
  List<TerminalNode> SEPs() => getTokens(HandlebarsParser.TOKEN_SEP);
  TerminalNode? SEP(int i) => getToken(HandlebarsParser.TOKEN_SEP, i);
  @override
  int get ruleIndex => RULE_pathSegments;
  @override
  T? accept<T>(ParseTreeVisitor<T> visitor) {
    if (visitor is HandlebarsParserVisitor<T>) {
      return visitor.visitPathSegments(this);
    } else {
      return visitor.visitChildren(this);
    }
  }
}
