
import sys
import os
import re
import json
import subprocess
import argparse

def parse_pubspec_lock(content):
    """Parses pubspec.lock to extract version, source, url, and sha256."""
    packages = {}
    current_pkg = None
    
    lines = content.split('\n')
    iterator = iter(lines)
    
    try:
        while True:
            line = next(iterator)
            if line.strip() == "packages:":
                break
    except StopIteration:
        return {}
        
    pkg_start = re.compile(r"^  (\w+):$")
    current_info = {}
    
    for line in iterator:
        if not line: continue
        m_pkg = pkg_start.match(line)
        if m_pkg:
            if current_pkg and current_info:
                packages[current_pkg] = current_info
            current_pkg = m_pkg.group(1)
            current_info = {"name": current_pkg}
            continue
            
        if not line.startswith(" "): break
            
        if current_pkg:
            clean_line = line.strip()
            if ": " in clean_line:
                key, value = clean_line.split(": ", 1)
                value = value.strip('"')
                if key == "version": current_info["version"] = value
                elif key == "source": current_info["source"] = value
                elif key == "url": current_info["url"] = value
                elif key == "sha256": current_info["sha256"] = value

    if current_pkg and current_info:
        packages[current_pkg] = current_info
    return packages

def get_dependency_graph(dart_bin, pkg_dir):
    """Runs 'dart pub deps --json' and extracts dependencies."""
    try:
        # Run pub get first to ensure resolution
        subprocess.check_call([dart_bin, "pub", "get"], cwd=pkg_dir, stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL)
        
        output = subprocess.check_output([dart_bin, "pub", "deps", "--json"], cwd=pkg_dir)
        data = json.loads(output)
        
        graph = {}
        for pkg in data.get("packages", []):
            name = pkg["name"]
            deps = pkg.get("dependencies", [])
            graph[name] = deps
        return graph
    except Exception as e:
        print(f"Error resolving dependencies: {e}", file=sys.stderr)
        return {}

def generate_starlark(lock_data, graph_data, output_file):
    """Generates dart_deps.bzl."""
    with open(output_file, 'w') as f:
        f.write("# Generated by rules_dart gazelle. DO NOT EDIT.\n\n")
        f.write("DART_PACKAGES = {\n")
        
        # Sort for deterministic output
        for name in sorted(lock_data.keys()):
            info = lock_data[name]
            # Only include hosted packages
            if info.get("source") != "hosted":
                continue
                
            deps = sorted(graph_data.get(name, []))
            
            f.write(f'    "{name}": {{\n')
            f.write(f'        "name": "{name}",\n')
            f.write(f'        "version": "{info.get("version", "")}",\n')
            f.write(f'        "sha256": "{info.get("sha256", "")}",\n')
            f.write(f'        "deps": {json.dumps(deps)},\n')
            
            # Construct URL if not present (or verify)
            # Standard: https://storage.googleapis.com/dart-archive/channels/stable/release/3.7.0/sdk/... NO
            # Pub: https://storage.googleapis.com/pub-packages/packages/name-version.tar.gz
            # pubspec.lock has 'url', typically "https://pub.dev". We need the archive URL.
            # We assume standard pub repo pattern for hosted.
            
            f.write(f'    }},\n')
            
        f.write("}\n")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dart_bin", required=True, help="Path to dart binary")
    parser.add_argument("--package_dir", required=True, help="Directory containing pubspec.yaml")
    parser.add_argument("--output", required=True, help="Output .bzl file path")
    
    args = parser.parse_args()
    
    lock_file = os.path.join(args.package_dir, "pubspec.lock")
    if not os.path.exists(lock_file):
        print(f"Error: {lock_file} not found.", file=sys.stderr)
        sys.exit(1)
        
    print(f"Parsing {lock_file}...")
    with open(lock_file, 'r') as f:
        lock_data = parse_pubspec_lock(f.read())
        
    print("Resolving dependency graph...")
    graph_data = get_dependency_graph(args.dart_bin, args.package_dir)
    
    print(f"Generating {args.output}...")
    generate_starlark(lock_data, graph_data, args.output)
    print("Done.")

if __name__ == "__main__":
    main()
